version: '3.1'
 
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: accountowner
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
  accountownerapp:
    depends_on:
      - db
    # image: my-registry:50000/codemazeblog/accountownerapp:build-2
    image: mannm/docker-series-local-registry-end:build-2
  integration:
    depends_on:
      - accountownerapp
    # image: my-registry:50000/codemazeblog/accountownerapp:test
    image: mannm/docker-series-local-registry-end:test
    build:
      context: .
      dockerfile: Dockerfile.Integration
      
volumes:
    dbdata:
